version: "2"

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo

linters:
  default: none
  enable:
    - gocyclo
    - staticcheck
    - govet
    - errcheck
  presets:
    - bugs
    - unused
  settings:
    gocyclo:
      min-complexity: 15
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (io.Closer).Close
        - (io.ReadCloser).Close
        - (net/http.ResponseWriter).Write
        - (*net/http.Server).Shutdown

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
